// Generated by gencpp from file drone_msgs/pose_velsResponse.msg
// DO NOT EDIT!


#ifndef DRONE_MSGS_MESSAGE_POSE_VELSRESPONSE_H
#define DRONE_MSGS_MESSAGE_POSE_VELSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_msgs
{
template <class ContainerAllocator>
struct pose_velsResponse_
{
  typedef pose_velsResponse_<ContainerAllocator> Type;

  pose_velsResponse_()
    {
    }
  pose_velsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::drone_msgs::pose_velsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_msgs::pose_velsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pose_velsResponse_

typedef ::drone_msgs::pose_velsResponse_<std::allocator<void> > pose_velsResponse;

typedef boost::shared_ptr< ::drone_msgs::pose_velsResponse > pose_velsResponsePtr;
typedef boost::shared_ptr< ::drone_msgs::pose_velsResponse const> pose_velsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_msgs::pose_velsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace drone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::pose_velsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::pose_velsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::pose_velsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::drone_msgs::pose_velsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_msgs/pose_velsResponse";
  }

  static const char* value(const ::drone_msgs::pose_velsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::drone_msgs::pose_velsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_velsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_msgs::pose_velsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::drone_msgs::pose_velsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MSGS_MESSAGE_POSE_VELSRESPONSE_H
